import Link from "next/link";
import type { Route } from "next";
import type { ReactNode } from "react";

import { ProductCompanyEvidence } from "@/components/product-company-evidence";
import { ProductCompanyComparison, ProductTrendExplorer } from "@/components/product-reset-client";
import type { ProductCompany, ProductLayer, ProductMetric, ProductRanking, ProductResetAnalytics } from "@/src/server/product-reset/analytics";
import type { Tranche4PreviewModel } from "@/src/server/tranche4/preview-model";
import { publicMetricLabel } from "@/src/ui/public-labels";

function money(metric: ProductMetric | undefined) {
  if (!metric || metric.status === "unavailable" || metric.value == null) return "Unavailable";
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(Number(metric.value));
}
function pct(metric: ProductMetric | undefined) { return !metric || metric.status === "unavailable" || metric.percent == null ? "Unavailable" : `${metric.percent >= 0 ? "+" : ""}${metric.percent.toFixed(1)}%`; }
function titleCase(value: string) { return value.split("_").map((item) => item === "ai" ? "AI" : item.charAt(0).toUpperCase() + item.slice(1)).join(" "); }

function Hero({ eyebrow, title, accent, copy, children }: { eyebrow: string; title: string; accent: string; copy: string; children?: ReactNode }) {
  return <section className="pr-hero"><div className="pr-node" /><p className="pr-eyebrow">{eyebrow}</p><h1>{title} <em>{accent}</em></h1><p className="pr-lede">{copy}</p>{children}</section>;
}
function CommonStatus({ analytics }: { analytics: ProductResetAnalytics }) {
  const p = analytics.commonPeriod;
  return <section className="pr-status" aria-label="Common-period data status"><div><strong>{p.commonComparisonQuarter} common comparison window</strong><span>Data through {p.dataThrough}</span></div><div><b>{p.reconciledCompanyCount} / {p.totalTrackedCompanyCount}</b><span>companies reconciled</span></div><div><b>{p.newerPartialQuarterCompanyCount} / {p.totalTrackedCompanyCount}</b><span>newer-quarter updates received</span></div></section>;
}
function aggregate(analytics: ProductResetAnalytics, key: keyof ProductCompany["metrics"]) {
  const valid = analytics.companies.map((company) => company.metrics[key]).filter((metric) => metric.status !== "unavailable" && metric.value);
  return { value: valid.reduce((sum, metric) => sum + Number(metric.value), 0), valid: valid.length };
}
function Snapshot({ analytics }: { analytics: ProductResetAnalytics }) {
  const revenue = aggregate(analytics, "ttmRevenue"); const capex = aggregate(analytics, "ttmCapex"); const rd = aggregate(analytics, "ttmResearchAndDevelopment");
  const compact = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 2 }).format(value);
  return <div className="pr-snapshot"><article><span>Tracked TTM Revenue</span><strong>{compact(revenue.value)}</strong><small>{revenue.valid}/17 comparable</small></article><article><span>Tracked TTM Capex</span><strong>{compact(capex.value)}</strong><small>{capex.valid}/17 comparable · company-wide</small></article><article><span>Tracked TTM R&D</span><strong>{compact(rd.value)}</strong><small>{rd.valid}/17 comparable</small></article><article><span>Cohort Capex intensity</span><strong>{(capex.value / revenue.value * 100).toFixed(1)}%</strong><small>Valid-value aggregate, not AI spending</small></article></div>;
}
function Section({ index, eyebrow, title, copy, children, dark = false }: { index: string; eyebrow: string; title: string; copy: string; children: ReactNode; dark?: boolean }) {
  return <section className={`pr-section ${dark ? "pr-dark" : ""}`}><header><p className="pr-eyebrow">{index} / {eyebrow}</p><div><h2>{title}</h2><p>{copy}</p></div></header>{children}</section>;
}
function RankingCard({ title, copy, values, format = "money" }: { title: string; copy: string; values: ProductRanking[]; format?: "money" | "percent" }) {
  const top = values.slice(0, 6); const max = Math.max(...top.map((item) => Number(item.value ?? item.percent ?? 0)), 1);
  return <article className="pr-ranking"><p className="pr-eyebrow">{copy}</p><h3>{title}</h3>{top.map((item) => { const numeric = Number(item.value ?? item.percent ?? 0); return <div className="pr-rank-row" key={item.entityKey}><span>{String(item.rank).padStart(2, "0")}</span><Link href={`/companies/${encodeURIComponent(item.entityKey)}` as Route}>{item.displayName}</Link><i><b style={{ width: `${Math.max(numeric / max * 100, 3)}%` }} /></i><strong>{format === "percent" ? `${item.percent?.toFixed(1)}%` : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", notation: "compact", maximumFractionDigits: 1 }).format(Number(item.value))}</strong></div>;})}</article>;
}
function LayerCard({ layer }: { layer: ProductLayer }) {
  return <article className={`pr-layer ${layer.layerKey}`}><p className="pr-eyebrow">{layer.layerKey.replace("layer_", "Layer ")} / {layer.label}</p><h3>{layer.trackedCompanyCount} companies</h3><div className="pr-layer-metrics"><div><span>TTM Revenue</span><strong>{money(layer.ttmRevenue)}</strong></div><div><span>TTM Capex</span><strong>{money(layer.ttmCapex)}</strong></div><div><span>TTM R&D</span><strong>{money(layer.ttmResearchAndDevelopment)}</strong></div><div><span>Capex intensity</span><strong>{pct(layer.ttmCapexIntensity)}</strong></div></div><p>{layer.constituents.map((item) => item.displayName).join(" · ")}</p><small>Company-wide financials; {layer.ttmCapex.validCompanyCount}/{layer.trackedCompanyCount} valid for Capex and {layer.ttmResearchAndDevelopment.validCompanyCount}/{layer.trackedCompanyCount} for R&D.</small></article>;
}
function LatestPulse({ analytics }: { analytics: ProductResetAnalytics }) {
  const revenueRanks = new Map(analytics.rankings.ttmRevenue.map((item) => [item.entityKey, item.rank])); const growthRanks = new Map(analytics.rankings.revenueYoyGrowth.map((item) => [item.entityKey, item.rank]));
  return <div className="pr-pulse">{analytics.companies.slice().sort((a, b) => b.latestReported.periodEnd.localeCompare(a.latestReported.periodEnd)).slice(0, 8).map((company) => <article key={company.entityKey}><span>{company.latestReported.reportingQuarter}</span><div><h3>{company.displayName}</h3><p><b>{company.latestReported.newerThanCommonWindow ? "Newer filing received" : "Common baseline current"}</b><b>#{revenueRanks.get(company.entityKey)} TTM revenue</b><b>#{growthRanks.get(company.entityKey)} revenue growth</b>{company.latestReported.newerThanCommonWindow ? <b>Not yet cohort baseline</b> : null}</p></div><Link href={`/companies/${encodeURIComponent(company.entityKey)}` as Route}>Company →</Link></article>)}</div>;
}

export function ProductOverview({ analytics }: { analytics: ProductResetAnalytics }) {
  return <><Hero eyebrow="AI economy intelligence" title="Follow the money behind the" accent="AI buildout." copy="A common-period view of scale, capital investment and research across 17 public companies, grounded in official filings and designed for comparison."><div className="pr-hero-actions"><Link href="/companies">Compare companies</Link><Link href="/data">Inspect the data</Link></div></Hero><CommonStatus analytics={analytics} /><Section index="01" eyebrow="Cohort snapshot" title="The tracked economy, on one comparable clock." copy="TTM measures end at the latest quarter reached by the full cohort. Newer company filings remain visible without moving the baseline early."><Snapshot analytics={analytics} /></Section><Section index="02" eyebrow="Main trend" title="Scale and investment are moving together, but not evenly." copy="Switch between company-wide Revenue, Capex and R&D. Every series ends at the same common comparison window." dark><ProductTrendExplorer companies={analytics.companies} commonQuarter={analytics.commonPeriod.commonComparisonQuarter} /></Section><Section index="03" eyebrow="Who is driving it" title="Rank the cohort without inventing a narrative." copy="Deterministic ranks include only comparable TTM values; unavailable values never enter as zero."><div className="pr-rank-grid"><RankingCard title="Largest capital programs" copy="TTM Capex" values={analytics.rankings.ttmCapex} /><RankingCard title="Investment relative to scale" copy="Capex intensity" values={analytics.rankings.ttmCapexIntensity} format="percent" /></div></Section><Section index="04" eyebrow="AI Stack economics" title="Where companies sit becomes economically useful." copy="Each company rolls up once by primary layer. These are company-wide financials of tracked companies, not AI-segment totals."><div className="pr-layer-grid">{analytics.layerRollups.map((layer) => <LayerCard layer={layer} key={layer.layerKey} />)}</div><div className="pr-layer-five"><span>Layer 5</span><strong>Users & economic outcomes</strong><p>No company-financial rollup. This layer will hold adoption and economic-outcome measures when supported by production data.</p></div></Section><Section index="05" eyebrow="Latest quarter" title="Recent filings, without moving the cohort baseline early." copy="Deterministic status and rank labels show what changed. No generated commentary is used."><LatestPulse analytics={analytics} /></Section><section className="pr-paths"><div><p className="pr-eyebrow">Continue exploring</p><h2>Move from the cohort to the evidence.</h2></div><Link href="/companies">Compare companies →</Link><Link href="/ai-stack">Explore the AI Stack →</Link><Link href="/data">Open Data →</Link></section></>;
}
export function ProductAiStack({ analytics }: { analytics: ProductResetAnalytics }) {
  const maxCapex = Math.max(...analytics.layerRollups.map((item) => Number(item.ttmCapex.value ?? 0)), 1);
  return <><Hero eyebrow="AI Stack economics" title="See where the" accent="economic weight sits." copy="Primary roles organize company-wide financial scale without double counting secondary positions across the stack." /><CommonStatus analytics={analytics} /><Section index="01" eyebrow="Layer economics" title="Four layers, one contribution per company." copy="Revenue, Capex and R&D are company-wide figures for tracked constituents, not AI-segment revenue or market totals."><div className="pr-layer-grid">{analytics.layerRollups.map((layer) => <LayerCard layer={layer} key={layer.layerKey} />)}</div></Section><Section index="02" eyebrow="Capital concentration" title="Infrastructure carries the largest tracked capital programs." copy="Compare valid company-wide TTM Capex by primary layer; disclosed coverage accompanies every rollup." dark><div className="pr-layer-bars">{analytics.layerRollups.map((layer) => <div key={layer.layerKey}><span>{layer.label}</span><i><b style={{ width: `${Math.max(Number(layer.ttmCapex.value ?? 0) / maxCapex * 100, 2)}%` }} /></i><strong>{money(layer.ttmCapex)}</strong></div>)}</div></Section><Section index="03" eyebrow="Cross-stack reality" title="Primary role gives structure. Secondary roles show overlap." copy="Secondary roles provide context but never duplicate company-wide financials."><div className="pr-role-grid">{analytics.companies.filter((company) => company.secondaryRoles.length).map((company) => <article key={company.entityKey}><p className="pr-eyebrow">{company.displayName}</p><h3>Primary · {titleCase(company.primaryLayer)}</h3><p>Secondary · {company.secondaryRoles.map(titleCase).join(" · ")}</p></article>)}</div></Section><div className="pr-layer-five"><span>Layer 5</span><strong>Users & economic outcomes</strong><p>Kept distinct from company-financial rollups; no fabricated totals.</p></div></>;
}
export function ProductTrends({ analytics }: { analytics: ProductResetAnalytics }) {
  return <><Hero eyebrow="Trends" title="See how the buildout is" accent="changing." copy="A deeper workspace for company-wide scale, investment, research and intensity on a shared comparison endpoint." /><CommonStatus analytics={analytics} /><Section index="01" eyebrow="Five-year view" title="One workspace, three financial questions." copy="Revenue, Capex and R&D share the same visual grammar and common endpoint." dark><ProductTrendExplorer companies={analytics.companies} commonQuarter={analytics.commonPeriod.commonComparisonQuarter} /></Section><Section index="02" eyebrow="Intensity" title="Big spenders are not always the hardest investors." copy="Absolute investment and investment relative to revenue remain separate views."><div className="pr-rank-grid"><RankingCard title="Capex / TTM Revenue" copy="Capex intensity" values={analytics.rankings.ttmCapexIntensity} format="percent" /><RankingCard title="R&D / TTM Revenue" copy="R&D intensity" values={analytics.rankings.ttmResearchAndDevelopmentIntensity} format="percent" /></div></Section><Section index="03" eyebrow="Recent reports" title="New company data stays visible without breaking comparability." copy={`${analytics.commonPeriod.newerPartialQuarterCompanyCount} companies have a newer report than the common baseline.`}><LatestPulse analytics={analytics} /></Section></>;
}
export function ProductCompanies({ analytics }: { analytics: ProductResetAnalytics }) {
  return <><Hero eyebrow="Companies" title="Compare the cohort before you" accent="drill down." copy="Choose up to four companies across scale, growth, investment and research. Unavailable values stay explicit." /><CommonStatus analytics={analytics} /><Section index="01" eyebrow="Comparison workspace" title="Put like-for-like TTM metrics side by side." copy="All values use each company's latest valid fiscal endpoint within the same common reporting window."><ProductCompanyComparison companies={analytics.companies} /></Section><Section index="02" eyebrow="Company list" title="A compact route into every company." copy="Sort order follows TTM Revenue rank; profile pages hold the deeper trajectory and evidence."><div className="pr-company-list">{analytics.rankings.ttmRevenue.map((ranked) => { const company = analytics.companies.find((item) => item.entityKey === ranked.entityKey)!; return <Link href={`/companies/${encodeURIComponent(company.entityKey)}` as Route} key={company.entityKey}><span>#{ranked.rank}</span><strong>{company.displayName}</strong><small>{titleCase(company.primaryLayer)}</small><b>{money(company.metrics.ttmRevenue)}</b><em>Open →</em></Link>;})}</div></Section></>;
}
function HistoryChart({ company, metricKey }: { company: ProductCompany; metricKey: string }) {
  const values = company.annualHistory[metricKey] ?? []; const max = Math.max(...values.map((item) => Number(item.value)), 1);
  if (!values.length) return <article className="pr-mini-trend"><h3>{publicMetricLabel(metricKey)}</h3><p>Comparable annual history unavailable.</p></article>;
  const points = values.map((item, index) => ({ item, x: 40 + index * (280 / Math.max(values.length - 1, 1)), y: 120 - Number(item.value) / max * 82 }));
  return <article className="pr-mini-trend"><h3>{publicMetricLabel(metricKey)}</h3><svg viewBox="0 0 360 150" role="img" aria-label={`${company.displayName} ${publicMetricLabel(metricKey)} annual trend`}><polyline points={points.map((point) => `${point.x},${point.y}`).join(" ")} />{points.map(({ item, x, y }) => <g key={item.observationId}><circle cx={x} cy={y} r="4" /><text x={x} y="142">FY{item.fiscalYear}</text></g>)}</svg><p>{values.length} eligible completed fiscal years</p></article>;
}
export function ProductCompanyDetail({ analytics, companyModel, entityKey }: { analytics: ProductResetAnalytics; companyModel: Tranche4PreviewModel; entityKey: string }) {
  const company = analytics.companies.find((item) => item.entityKey === entityKey); const entity = companyModel.entities.find((item) => item.entityKey === entityKey); if (!company || !entity) return null;
  const annual = companyModel.annual.chartReadyValues.filter((item) => item.entityKey === entityKey); const interim = companyModel.interim.chartReadyValues.filter((item) => item.entityKey === entityKey); const histories = companyModel.histories.chartReadyValues.filter((item) => item.entityKey === entityKey); const observations = companyModel.observations.filter((item) => item.entityKey === entityKey); const interimHistory = companyModel.interimHistory.filter((item) => item.entityKey === entityKey);
  return <><section className="pr-company-hero"><Link href="/companies">← Companies</Link><p className="pr-eyebrow">Company intelligence</p><h1>{company.displayName}</h1><p>Common-period scale, investment and research first. Newer reported data and exact evidence remain distinct below.</p><span>{titleCase(company.primaryLayer)}</span></section><CommonStatus analytics={analytics} /><div className="pr-snapshot pr-company-snapshot"><article><span>TTM Revenue</span><strong>{money(company.metrics.ttmRevenue)}</strong><small>{analytics.commonPeriod.commonComparisonQuarter} common window</small></article><article><span>TTM Capex</span><strong>{money(company.metrics.ttmCapex)}</strong><small>Company-wide · {pct(company.metrics.ttmCapexIntensity)} of Revenue</small></article><article><span>TTM R&D</span><strong>{money(company.metrics.ttmResearchAndDevelopment)}</strong><small>{pct(company.metrics.ttmResearchAndDevelopmentIntensity)} of Revenue</small></article><article><span>Revenue growth</span><strong>{pct(company.metrics.revenueYoyGrowth)}</strong><small>TTM year over year</small></article></div><Section index="01" eyebrow="Trajectory" title="How the company is changing." copy="Up to five completed fiscal years, separated by metric and ending before the common baseline."><div className="pr-mini-trends"><HistoryChart company={company} metricKey="revenue" /><HistoryChart company={company} metricKey="capital_expenditure" /><HistoryChart company={company} metricKey="research_and_development" /></div></Section><Section index="02" eyebrow="Latest reporting" title="Newest company data can be visible before the cohort moves." copy={`Common baseline: ${company.commonWindowAnchor.reportingQuarter}, ending ${company.commonWindowAnchor.periodEnd}. Latest company report: ${company.latestReported.reportingQuarter}, ending ${company.latestReported.periodEnd}.`}><div className="pr-report-status"><span>{company.latestReported.newerThanCommonWindow ? "Newer report received" : "Aligned with common baseline"}</span><strong>{company.latestReported.reportingQuarter}</strong><p>{company.latestReported.newerThanCommonWindow ? "Visible as company context; not used to move cross-company comparisons." : "This report is within the common comparison window."}</p></div></Section><section className="pr-evidence"><ProductCompanyEvidence annual={annual} interim={interim} interimHistory={interimHistory} histories={histories} observations={observations} /></section></>;
}
